name: Build CUDA Image

on:
  workflow_dispatch:
    inputs:
      cuda_version:
        description: 'CUDA version'
        required: false
        default: '12.4.1'
        type: string
      cuda_architectures:
        description: 'CUDA architectures'
        required: false
        default: '86'
        type: string
      go_version:
        description: 'Go version'
        required: false
        default: '1.25.2'
        type: string
  push:
    branches: [main]
    paths:
      - 'Dockerfile.cuda'

env:
  REGISTRY: git.tomfos.tr
  IMAGE_TAG: build-cuda

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: ${{ env.BUILDKIT_ENDPOINT != '' && 'remote' || 'docker-container' }}
          endpoint: ${{ env.BUILDKIT_ENDPOINT || '' }}

      - name: Login to Forgejo Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and push CUDA image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.cuda
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }}
          build-args: |
            CUDA_ARCHITECTURES=${{ github.event.inputs.cuda_architectures || '86' }}
            GO_VERSION=${{ github.event.inputs.go_version || '1.25.2' }}
