name: CI/CD Pipeline

on:
  push:
    branches: [main, "tom/*"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: git.tomfos.tr

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: git.tomfos.tr/tom/llama-go:build-cuda
    env:
      LIBRARY_PATH: ${{ github.workspace }}
      C_INCLUDE_PATH: ${{ github.workspace }}
      LD_LIBRARY_PATH: ${{ github.workspace }}:${{ github.workspace }}/build/bin
      # Configure sccache for CMake builds
      CMAKE_C_COMPILER_LAUNCHER: sccache
      CMAKE_CXX_COMPILER_LAUNCHER: sccache
      CMAKE_CUDA_COMPILER_LAUNCHER: sccache
      # Enable GitHub Actions cache backend
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache dependencies
        uses: https://github.com/actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            Qwen3-0.6B-Q8_0.gguf
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup sccache
        uses: https://git.tomfos.tr/tom/sccache-action@v1

      - name: Build library
        run: |
          make libbinding.a

      - name: Debug - List built artifacts
        run: |
          echo "=== GPU Detection ==="
          nvidia-smi || echo "No GPU detected"
          echo "=== Files in build/bin ==="
          ls -la build/bin/ || echo "build/bin not found"
          echo "=== Files in workspace root ==="
          ls -la *.so *.a 2>/dev/null || echo "No .so or .a files in workspace root"
          echo "=== Current working directory ==="
          pwd
          echo "=== LD_LIBRARY_PATH ==="
          echo "$LD_LIBRARY_PATH"

      - name: Download test model
        run: |
          if [ ! -f Qwen3-0.6B-Q8_0.gguf ]; then
            wget -q https://huggingface.co/Qwen/Qwen3-0.6B-GGUF/resolve/main/Qwen3-0.6B-Q8_0.gguf
          fi

      - name: Run tests
        run: |
          TEST_MODEL=Qwen3-0.6B-Q8_0.gguf \
            go run github.com/onsi/ginkgo/v2/ginkgo --vv ./...

      - name: Run example
        run: |
          go run ./examples/simple -m Qwen3-0.6B-Q8_0.gguf -p 'Hello world' -n 50
